t2: e1
#	open output.png
	python mkimg2asm.py output.png > output.asm
	python mkimg2asm.py output1.png > output1.asm
	python mkimg2asm.py output2.png > output2.asm
	python mkimg2asm.py output3.png > output3.asm
	python mkimg2asm.py output4.png > output4.asm
	python mkimg2asm.py output5.png > output5.asm
	python mkimg2asm.py output6.png > output6.asm
	python mkimg2asm.py output7.png > output7.asm
	python mkimg2asm.py output8.png > output8.asm
	python mkimg2asm.py output9.png > output9.asm
	python mkimg2asm.py outputa.png > outputa.asm
	python mkimg2asm.py outputb.png > outputb.asm
	python mkimg2asm.py outputc.png > outputc.asm
	python mkimg2asm.py outputd.png > outputd.asm
e1:
	python mkimg2asm.py enemy1.png enemy1.json > enemy1.asm

