1:
	java -jar glass-0.6.jar main32k.asm main32k.rom
	#openmsx -carta main32k.rom -romtype Plain
	openmsx -carta main32k.rom

2:
	java -jar glass-0.6.jar main_ascii16.asm main_ascii16.rom
	openmsx -carta main_ascii16.rom -romtype ASCII16

clean:

	rm -f *.bin *.rom
